services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: conduit-mssql
    environment:
      SA_PASSWORD: "Conduit_Dev_2024!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
